// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzS75p16U-u0BAER7Mh7mm5QxWnVlLM1E',
    appId: '1:523230196876:web:27dc6ba8c02d12166137a9',
    messagingSenderId: '523230196876',
    projectId: 'example-ead6c',
    authDomain: 'example-ead6c.firebaseapp.com',
    storageBucket: 'example-ead6c.firebasestorage.app',
    measurementId: 'G-H510PDKXHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeEg9TBIwNrwYqZEYbaIJ-P-I9szzbI88',
    appId: '1:523230196876:android:75b24af3ddcd79896137a9',
    messagingSenderId: '523230196876',
    projectId: 'example-ead6c',
    storageBucket: 'example-ead6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr300jDQE5H4F2mEfr5JKDgF82N-berL8',
    appId: '1:523230196876:ios:c429f86b72beb9026137a9',
    messagingSenderId: '523230196876',
    projectId: 'example-ead6c',
    storageBucket: 'example-ead6c.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr300jDQE5H4F2mEfr5JKDgF82N-berL8',
    appId: '1:523230196876:ios:c429f86b72beb9026137a9',
    messagingSenderId: '523230196876',
    projectId: 'example-ead6c',
    storageBucket: 'example-ead6c.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzS75p16U-u0BAER7Mh7mm5QxWnVlLM1E',
    appId: '1:523230196876:web:f3eeb19c8dec34116137a9',
    messagingSenderId: '523230196876',
    projectId: 'example-ead6c',
    authDomain: 'example-ead6c.firebaseapp.com',
    storageBucket: 'example-ead6c.firebasestorage.app',
    measurementId: 'G-P85DSB6D8Z',
  );
}
